/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI;

import connectdb.ConnectDB;
import dao.HoaDon_DAO;
import dao.KhachHang_DAO;
import dao.NhanVien_DAO;
import dao.PhieuDatPhong_DAO;
import dao.Phong_DAO;
import entity.HoaDon;
import entity.KhachHang;
import entity.LoaiPhong;
import entity.NhanVien;
import entity.PhieuDatPhong;
import entity.Phong;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.event.TableModelListener;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author Duong Ngo Manh
 */
public class GUIDatPhongCho extends javax.swing.JFrame {
    KhachHang_DAO khachHang_dao = new KhachHang_DAO();
    PhieuDatPhong_DAO pdp_dao = new PhieuDatPhong_DAO();
    Phong_DAO p_dao = new Phong_DAO();
    NhanVien_DAO nhanVien_dao = new NhanVien_DAO();
    HoaDon_DAO hoaDon_dao = new HoaDon_DAO();
    DefaultTableModel dftblPDP ,dftblPC,dftblPindlg;
    /**
     * Creates new form GUIThongTinPhong
     */
    public GUIDatPhongCho() {
        try {
            ConnectDB.getInstance().connect();
	} catch (SQLException e) {
            e.printStackTrace();
	}
        setSize(1520, 780);
        setLocationRelativeTo(null);
        initComponents();
        dongHoNgay();
        dongHoGio();
    }
    
    private void dongHoGio(){
        new Thread(){
            public void run(){
                while(true){
                    Calendar ca = new GregorianCalendar();
                    int hour = ca.get(Calendar.HOUR);
                    int min = ca.get(Calendar.MINUTE);
                    int sec = ca.get(Calendar.SECOND);
                    lblGio.setText(hour +":"+min+":"+sec);
                }
            }
        }.start();
    }
    private void dongHoNgay(){
        new Thread(){
            public void run(){
                while(true){
                    Calendar ca = new GregorianCalendar();
                    int day = ca.get(Calendar.DATE);
                    int month = ca.get(Calendar.MONTH)+1;
                    int year = ca.get(Calendar.YEAR);
                    lblNgay.setText("Ngày "+day +","+month+" "+year);
                }
            }
        }.start();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dlgDatPhongCho = new javax.swing.JDialog();
        pnlDanhSachPhong = new javax.swing.JPanel();
        scrDanhSachPhong1 = new javax.swing.JScrollPane();
        tblDanhSachPhongIndlg = new javax.swing.JTable();
        btnXacNhanIndlgDatPhongCho = new javax.swing.JButton();
        btnQuayLaiFromDatPhongCho = new javax.swing.JButton();
        cboLoaiPhong = new javax.swing.JComboBox<>();
        lblSoNguoiToiDaindlg = new javax.swing.JLabel();
        lblMaLoaiPhong = new javax.swing.JLabel();
        txtSoNguoiToiDaindlg = new javax.swing.JTextField();
        btnTimPhong = new javax.swing.JButton();
        btnLamMoiIndlg = new javax.swing.JButton();
        lblMaPhongIndlg = new javax.swing.JLabel();
        txtMaPhongIndlg = new javax.swing.JTextField();
        pnlTieuDe3 = new javax.swing.JPanel();
        lblTieuDe = new javax.swing.JLabel();
        lblNgay = new javax.swing.JLabel();
        lblGio = new javax.swing.JLabel();
        pnlDanhSachPhong1 = new javax.swing.JPanel();
        scrDanhSachPhong = new javax.swing.JScrollPane();
        tblDanhSachPhongCho = new javax.swing.JTable();
        pnlDanhSachPhieuDatPhong = new javax.swing.JPanel();
        scrDanhSachPhong2 = new javax.swing.JScrollPane();
        tblDanhSachPhieuDatPhong = new javax.swing.JTable();
        lblMaPhieuDatPhong = new javax.swing.JLabel();
        lblMaNhanVien = new javax.swing.JLabel();
        txtMaPhieuDatPhong = new javax.swing.JTextField();
        cboNhanVien = new javax.swing.JComboBox<>();
        lblMaKhachHang1 = new javax.swing.JLabel();
        lblMaPhong = new javax.swing.JLabel();
        txtMaPhong = new javax.swing.JTextField();
        dcNgayDatPhong = new com.toedter.calendar.JDateChooser();
        btnNhanPhongCho = new javax.swing.JButton();
        btnDatPhongCho = new javax.swing.JButton();
        btnHuyPhongCho = new javax.swing.JButton();
        btnLamMoi = new javax.swing.JButton();
        pnlThongTinKhachHang = new javax.swing.JPanel();
        txtSoDienThoai = new javax.swing.JTextField();
        lblTenKhachHang = new javax.swing.JLabel();
        lblNgayLap3 = new javax.swing.JLabel();
        btnKiemTraSDT = new javax.swing.JButton();
        txtMaKhachHang = new javax.swing.JTextField();
        lblNgayLap1 = new javax.swing.JLabel();
        txtTenKhachHang = new javax.swing.JTextField();
        mnuTong = new javax.swing.JMenuBar();
        mnHeThong = new javax.swing.JMenu();
        mniTrangChu = new javax.swing.JMenuItem();
        mniTroGiup = new javax.swing.JMenuItem();
        mniDangXuat = new javax.swing.JMenuItem();
        mnuPhong = new javax.swing.JMenu();
        mniCapNhatPhong = new javax.swing.JMenuItem();
        mniCapNhatLoaiPhong = new javax.swing.JMenuItem();
        mniTimKiemPhong = new javax.swing.JMenuItem();
        mniDatPhong = new javax.swing.JMenuItem();
        mniDatPhongCho = new javax.swing.JMenuItem();
        mnuNhanVien = new javax.swing.JMenu();
        mniCapNhatNhanVien = new javax.swing.JMenuItem();
        mniTimKiemNhanVien = new javax.swing.JMenuItem();
        mnuKhachHang = new javax.swing.JMenu();
        mniCapNhatKhachHang = new javax.swing.JMenuItem();
        mniTimKiemKhachHang = new javax.swing.JMenuItem();
        mnuThongKe = new javax.swing.JMenu();
        mniThongKeDoanhThu = new javax.swing.JMenuItem();
        mniThongKeDoanhThuTheoKhachHang = new javax.swing.JMenuItem();
        mnuHoaDon = new javax.swing.JMenu();
        mniLapHoaDon = new javax.swing.JMenuItem();
        mniThanhToan = new javax.swing.JMenuItem();
        mnuDichVu = new javax.swing.JMenu();
        mniCapNhatDichVu = new javax.swing.JMenuItem();
        mniTimKiemDichVu = new javax.swing.JMenuItem();
        mnuKhuyenMai = new javax.swing.JMenu();
        mniCapNhatKhuyenMai = new javax.swing.JMenuItem();
        mniTimKiemKhuyenMai = new javax.swing.JMenuItem();

        dlgDatPhongCho.setModal(true);
        dlgDatPhongCho.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dlgDatPhongChoMouseClicked(evt);
            }
        });
        dlgDatPhongCho.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                dlgDatPhongChoComponentShown(evt);
            }
        });

        pnlDanhSachPhong.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "DANH SÁCH PHÒNG\n\n", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N
        pnlDanhSachPhong.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                pnlDanhSachPhongComponentShown(evt);
            }
        });
        pnlDanhSachPhong.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblDanhSachPhongIndlg.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã phòng", "Loại phòng", "Tên phòng", "Giá phòng", "Số người tối đa", "Trạng thái"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.Float.class, java.lang.Integer.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblDanhSachPhongIndlg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDanhSachPhongIndlgMouseClicked(evt);
            }
        });
        tblDanhSachPhongIndlg.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                tblDanhSachPhongIndlgComponentShown(evt);
            }
        });
        scrDanhSachPhong1.setViewportView(tblDanhSachPhongIndlg);

        pnlDanhSachPhong.add(scrDanhSachPhong1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 710, 520));

        btnXacNhanIndlgDatPhongCho.setBackground(new java.awt.Color(153, 255, 255));
        btnXacNhanIndlgDatPhongCho.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnXacNhanIndlgDatPhongCho.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/danhmuc.png"))); // NOI18N
        btnXacNhanIndlgDatPhongCho.setText("Thêm vào danh sách chờ");
        btnXacNhanIndlgDatPhongCho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXacNhanIndlgDatPhongChoActionPerformed(evt);
            }
        });

        btnQuayLaiFromDatPhongCho.setBackground(new java.awt.Color(255, 51, 51));
        btnQuayLaiFromDatPhongCho.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnQuayLaiFromDatPhongCho.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/back.png"))); // NOI18N
        btnQuayLaiFromDatPhongCho.setText("Đóng");

        cboLoaiPhong.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "LP001", "LP002" }));

        lblSoNguoiToiDaindlg.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblSoNguoiToiDaindlg.setText("Số người tối đa:");

        lblMaLoaiPhong.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblMaLoaiPhong.setText("Loại phòng:");

        txtSoNguoiToiDaindlg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSoNguoiToiDaindlgActionPerformed(evt);
            }
        });

        btnTimPhong.setBackground(new java.awt.Color(153, 255, 255));
        btnTimPhong.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnTimPhong.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/search.png"))); // NOI18N
        btnTimPhong.setText("Tìm kiếm");
        btnTimPhong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimPhongActionPerformed(evt);
            }
        });

        btnLamMoiIndlg.setBackground(new java.awt.Color(153, 255, 153));
        btnLamMoiIndlg.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnLamMoiIndlg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/clean.png"))); // NOI18N
        btnLamMoiIndlg.setText("Làm mới");
        btnLamMoiIndlg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLamMoiIndlgActionPerformed(evt);
            }
        });

        lblMaPhongIndlg.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblMaPhongIndlg.setText("Mã phòng:");

        javax.swing.GroupLayout dlgDatPhongChoLayout = new javax.swing.GroupLayout(dlgDatPhongCho.getContentPane());
        dlgDatPhongCho.getContentPane().setLayout(dlgDatPhongChoLayout);
        dlgDatPhongChoLayout.setHorizontalGroup(
            dlgDatPhongChoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dlgDatPhongChoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlDanhSachPhong, javax.swing.GroupLayout.PREFERRED_SIZE, 735, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(dlgDatPhongChoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dlgDatPhongChoLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(dlgDatPhongChoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(dlgDatPhongChoLayout.createSequentialGroup()
                                .addComponent(lblSoNguoiToiDaindlg)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtSoNguoiToiDaindlg))
                            .addGroup(dlgDatPhongChoLayout.createSequentialGroup()
                                .addComponent(lblMaLoaiPhong)
                                .addGap(47, 47, 47)
                                .addComponent(cboLoaiPhong, 0, 197, Short.MAX_VALUE))
                            .addGroup(dlgDatPhongChoLayout.createSequentialGroup()
                                .addGroup(dlgDatPhongChoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(dlgDatPhongChoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(btnXacNhanIndlgDatPhongCho)
                                        .addGroup(dlgDatPhongChoLayout.createSequentialGroup()
                                            .addComponent(btnTimPhong, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(btnLamMoiIndlg)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dlgDatPhongChoLayout.createSequentialGroup()
                                        .addComponent(lblMaPhongIndlg, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtMaPhongIndlg, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(23, 23, 23))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dlgDatPhongChoLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnQuayLaiFromDatPhongCho, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(17, 17, 17))))
        );
        dlgDatPhongChoLayout.setVerticalGroup(
            dlgDatPhongChoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dlgDatPhongChoLayout.createSequentialGroup()
                .addGroup(dlgDatPhongChoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(dlgDatPhongChoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(pnlDanhSachPhong, javax.swing.GroupLayout.PREFERRED_SIZE, 563, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(dlgDatPhongChoLayout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addGroup(dlgDatPhongChoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cboLoaiPhong, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblMaLoaiPhong))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(dlgDatPhongChoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtSoNguoiToiDaindlg, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblSoNguoiToiDaindlg))
                        .addGap(18, 18, 18)
                        .addGroup(dlgDatPhongChoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnTimPhong, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnLamMoiIndlg, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(dlgDatPhongChoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblMaPhongIndlg, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMaPhongIndlg, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addComponent(btnXacNhanIndlgDatPhongCho, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnQuayLaiFromDatPhongCho, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlTieuDe3.setBackground(new java.awt.Color(102, 0, 0));

        lblTieuDe.setBackground(new java.awt.Color(102, 0, 0));
        lblTieuDe.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblTieuDe.setForeground(new java.awt.Color(242, 242, 242));
        lblTieuDe.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTieuDe.setText("ĐẶT PHÒNG CHỜ");

        lblNgay.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblNgay.setForeground(new java.awt.Color(255, 255, 255));
        lblNgay.setText("Ngày , Tháng Năm");

        lblGio.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblGio.setForeground(new java.awt.Color(255, 255, 255));
        lblGio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblGio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/alarm-clock.png"))); // NOI18N
        lblGio.setText("00:00:00");

        javax.swing.GroupLayout pnlTieuDe3Layout = new javax.swing.GroupLayout(pnlTieuDe3);
        pnlTieuDe3.setLayout(pnlTieuDe3Layout);
        pnlTieuDe3Layout.setHorizontalGroup(
            pnlTieuDe3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTieuDe3Layout.createSequentialGroup()
                .addGap(709, 709, 709)
                .addComponent(lblTieuDe)
                .addGap(259, 259, 259)
                .addComponent(lblGio)
                .addGap(18, 18, 18)
                .addComponent(lblNgay)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlTieuDe3Layout.setVerticalGroup(
            pnlTieuDe3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTieuDe3Layout.createSequentialGroup()
                .addGroup(pnlTieuDe3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlTieuDe3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pnlTieuDe3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNgay)
                            .addComponent(lblGio)))
                    .addGroup(pnlTieuDe3Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(lblTieuDe)))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        getContentPane().add(pnlTieuDe3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1520, 100));

        pnlDanhSachPhong1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "DANH SÁCH ĐẶT PHÒNG CHỜ\n", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N
        pnlDanhSachPhong1.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                pnlDanhSachPhong1ComponentShown(evt);
            }
        });
        pnlDanhSachPhong1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblDanhSachPhongCho.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã phòng", "Loại phòng", "Tên phòng", "Giá phòng", "Số người tối đa", "Trạng thái"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.Float.class, java.lang.Integer.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblDanhSachPhongCho.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDanhSachPhongChoMouseClicked(evt);
            }
        });
        tblDanhSachPhongCho.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                tblDanhSachPhongChoComponentShown(evt);
            }
        });
        scrDanhSachPhong.setViewportView(tblDanhSachPhongCho);

        pnlDanhSachPhong1.add(scrDanhSachPhong, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 680, 380));

        getContentPane().add(pnlDanhSachPhong1, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 300, 700, 420));

        pnlDanhSachPhieuDatPhong.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "DANH SÁCH ĐẶT PHÒNG", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N
        pnlDanhSachPhieuDatPhong.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                pnlDanhSachPhieuDatPhongComponentShown(evt);
            }
        });
        pnlDanhSachPhieuDatPhong.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblDanhSachPhieuDatPhong.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Mã phiếu đặt phòng", "Mã phòng", "Khách hàng", "Nhân viên", "Ngày đặt phòng", "Giờ nhận phòng"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblDanhSachPhieuDatPhong.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tblDanhSachPhieuDatPhongFocusLost(evt);
            }
        });
        tblDanhSachPhieuDatPhong.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDanhSachPhieuDatPhongMouseClicked(evt);
            }
        });
        tblDanhSachPhieuDatPhong.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                tblDanhSachPhieuDatPhongComponentShown(evt);
            }
        });
        scrDanhSachPhong2.setViewportView(tblDanhSachPhieuDatPhong);
        if (tblDanhSachPhieuDatPhong.getColumnModel().getColumnCount() > 0) {
            tblDanhSachPhieuDatPhong.getColumnModel().getColumn(1).setMinWidth(100);
        }

        pnlDanhSachPhieuDatPhong.add(scrDanhSachPhong2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 750, 380));

        getContentPane().add(pnlDanhSachPhieuDatPhong, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, 790, 420));

        lblMaPhieuDatPhong.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblMaPhieuDatPhong.setText("Mã phiếu đặt phòng:");
        getContentPane().add(lblMaPhieuDatPhong, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        lblMaNhanVien.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblMaNhanVien.setText("Nhân viên:");
        getContentPane().add(lblMaNhanVien, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, -1, -1));
        getContentPane().add(txtMaPhieuDatPhong, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 120, 190, 30));

        cboNhanVien.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                cboNhanVienComponentShown(evt);
            }
        });
        getContentPane().add(cboNhanVien, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 240, 190, 30));

        lblMaKhachHang1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblMaKhachHang1.setText("Ngày đặt phòng:");
        getContentPane().add(lblMaKhachHang1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, 30));

        lblMaPhong.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblMaPhong.setText("Mã phòng:");
        getContentPane().add(lblMaPhong, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, -1));
        getContentPane().add(txtMaPhong, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 160, 190, 30));
        getContentPane().add(dcNgayDatPhong, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 200, 193, 30));

        btnNhanPhongCho.setBackground(new java.awt.Color(153, 255, 153));
        btnNhanPhongCho.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnNhanPhongCho.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/add.png"))); // NOI18N
        btnNhanPhongCho.setText("Nhận phòng chờ");
        btnNhanPhongCho.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnNhanPhongCho.setName(""); // NOI18N
        btnNhanPhongCho.setOpaque(true);
        btnNhanPhongCho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNhanPhongChoActionPerformed(evt);
            }
        });
        getContentPane().add(btnNhanPhongCho, new org.netbeans.lib.awtextra.AbsoluteConstraints(1074, 140, 210, 62));
        btnNhanPhongCho.getAccessibleContext().setAccessibleDescription("");

        btnDatPhongCho.setBackground(new java.awt.Color(153, 255, 255));
        btnDatPhongCho.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnDatPhongCho.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/danhmuc.png"))); // NOI18N
        btnDatPhongCho.setText("Đặt phòng chờ");
        btnDatPhongCho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDatPhongChoActionPerformed(evt);
            }
        });
        getContentPane().add(btnDatPhongCho, new org.netbeans.lib.awtextra.AbsoluteConstraints(1075, 220, 210, 62));

        btnHuyPhongCho.setBackground(new java.awt.Color(255, 51, 51));
        btnHuyPhongCho.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnHuyPhongCho.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/cancel (1).png"))); // NOI18N
        btnHuyPhongCho.setText("Huỷ phòng chờ");
        btnHuyPhongCho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHuyPhongChoActionPerformed(evt);
            }
        });
        getContentPane().add(btnHuyPhongCho, new org.netbeans.lib.awtextra.AbsoluteConstraints(1310, 140, 200, 57));

        btnLamMoi.setBackground(new java.awt.Color(153, 255, 153));
        btnLamMoi.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnLamMoi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/clean.png"))); // NOI18N
        btnLamMoi.setText("Làm mới");
        btnLamMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLamMoiActionPerformed(evt);
            }
        });
        getContentPane().add(btnLamMoi, new org.netbeans.lib.awtextra.AbsoluteConstraints(1310, 220, 195, 57));

        pnlThongTinKhachHang.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thông Tin Khách Hàng", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N

        txtSoDienThoai.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        txtSoDienThoai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSoDienThoaiActionPerformed(evt);
            }
        });

        lblTenKhachHang.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTenKhachHang.setText("Tên Khách Hàng:");

        lblNgayLap3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblNgayLap3.setText("Số điện thoại:");

        btnKiemTraSDT.setBackground(new java.awt.Color(204, 204, 204));
        btnKiemTraSDT.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnKiemTraSDT.setText("Kiểm tra");
        btnKiemTraSDT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKiemTraSDTActionPerformed(evt);
            }
        });

        txtMaKhachHang.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N

        lblNgayLap1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblNgayLap1.setText("Mã khách hàng:");

        txtTenKhachHang.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N

        javax.swing.GroupLayout pnlThongTinKhachHangLayout = new javax.swing.GroupLayout(pnlThongTinKhachHang);
        pnlThongTinKhachHang.setLayout(pnlThongTinKhachHangLayout);
        pnlThongTinKhachHangLayout.setHorizontalGroup(
            pnlThongTinKhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlThongTinKhachHangLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlThongTinKhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTenKhachHang)
                    .addComponent(lblNgayLap3)
                    .addComponent(lblNgayLap1))
                .addGap(18, 18, 18)
                .addGroup(pnlThongTinKhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtTenKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMaKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlThongTinKhachHangLayout.createSequentialGroup()
                        .addComponent(txtSoDienThoai, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnKiemTraSDT)))
                .addGap(13, 13, 13))
        );
        pnlThongTinKhachHangLayout.setVerticalGroup(
            pnlThongTinKhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlThongTinKhachHangLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlThongTinKhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNgayLap3)
                    .addComponent(txtSoDienThoai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnKiemTraSDT, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlThongTinKhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTenKhachHang)
                    .addComponent(txtTenKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(pnlThongTinKhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNgayLap1)
                    .addComponent(txtMaKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        getContentPane().add(pnlThongTinKhachHang, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 110, -1, 190));

        mnuTong.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        mnHeThong.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/system.png"))); // NOI18N
        mnHeThong.setText("Hệ Thống");
        mnHeThong.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        mniTrangChu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ESCAPE, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mniTrangChu.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        mniTrangChu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/24-hours.png"))); // NOI18N
        mniTrangChu.setText("Trang chủ");
        mniTrangChu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniTrangChuActionPerformed(evt);
            }
        });
        mnHeThong.add(mniTrangChu);

        mniTroGiup.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        mniTroGiup.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/detail.png"))); // NOI18N
        mniTroGiup.setText("Trợ giúp");
        mniTroGiup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniTroGiupActionPerformed(evt);
            }
        });
        mnHeThong.add(mniTroGiup);

        mniDangXuat.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        mniDangXuat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/DangXuat.png"))); // NOI18N
        mniDangXuat.setText("Đăng xuất");
        mnHeThong.add(mniDangXuat);

        mnuTong.add(mnHeThong);

        mnuPhong.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/home.png"))); // NOI18N
        mnuPhong.setText("Phòng");
        mnuPhong.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        mniCapNhatPhong.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        mniCapNhatPhong.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/menu.png"))); // NOI18N
        mniCapNhatPhong.setText("Cập nhật phòng");
        mniCapNhatPhong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniCapNhatPhongActionPerformed(evt);
            }
        });
        mnuPhong.add(mniCapNhatPhong);

        mniCapNhatLoaiPhong.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        mniCapNhatLoaiPhong.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/description.png"))); // NOI18N
        mniCapNhatLoaiPhong.setText("Cập nhật loại phòng");
        mniCapNhatLoaiPhong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniCapNhatLoaiPhongActionPerformed(evt);
            }
        });
        mnuPhong.add(mniCapNhatLoaiPhong);

        mniTimKiemPhong.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        mniTimKiemPhong.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-search-24.png"))); // NOI18N
        mniTimKiemPhong.setText("Tìm kiếm phòng");
        mniTimKiemPhong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniTimKiemPhongActionPerformed(evt);
            }
        });
        mnuPhong.add(mniTimKiemPhong);

        mniDatPhong.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        mniDatPhong.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/televisions.png"))); // NOI18N
        mniDatPhong.setText("Đặt phòng");
        mniDatPhong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniDatPhongActionPerformed(evt);
            }
        });
        mnuPhong.add(mniDatPhong);

        mniDatPhongCho.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        mniDatPhongCho.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/lich_lam.png"))); // NOI18N
        mniDatPhongCho.setText("Đặt phòng chờ");
        mniDatPhongCho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniDatPhongChoActionPerformed(evt);
            }
        });
        mnuPhong.add(mniDatPhongCho);

        mnuTong.add(mnuPhong);

        mnuNhanVien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/nhanvien.png"))); // NOI18N
        mnuNhanVien.setText("Nhân viên");
        mnuNhanVien.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        mniCapNhatNhanVien.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        mniCapNhatNhanVien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/adminLogin.png"))); // NOI18N
        mniCapNhatNhanVien.setText("Cập nhật nhân viên");
        mniCapNhatNhanVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniCapNhatNhanVienActionPerformed(evt);
            }
        });
        mnuNhanVien.add(mniCapNhatNhanVien);

        mniTimKiemNhanVien.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        mniTimKiemNhanVien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/customer-service.png"))); // NOI18N
        mniTimKiemNhanVien.setText("Tìm kiếm nhân viên");
        mniTimKiemNhanVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniTimKiemNhanVienActionPerformed(evt);
            }
        });
        mnuNhanVien.add(mniTimKiemNhanVien);

        mnuTong.add(mnuNhanVien);

        mnuKhachHang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/khachHang.png"))); // NOI18N
        mnuKhachHang.setText("Khách hàng");
        mnuKhachHang.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        mniCapNhatKhachHang.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        mniCapNhatKhachHang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/customer.png"))); // NOI18N
        mniCapNhatKhachHang.setText("Cập nhật khách hàng");
        mniCapNhatKhachHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniCapNhatKhachHangActionPerformed(evt);
            }
        });
        mnuKhachHang.add(mniCapNhatKhachHang);

        mniTimKiemKhachHang.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        mniTimKiemKhachHang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/help (1).png"))); // NOI18N
        mniTimKiemKhachHang.setText("Tìm kiếm khách hàng");
        mniTimKiemKhachHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniTimKiemKhachHangActionPerformed(evt);
            }
        });
        mnuKhachHang.add(mniTimKiemKhachHang);

        mnuTong.add(mnuKhachHang);

        mnuThongKe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/thongke.png"))); // NOI18N
        mnuThongKe.setText("Thống Kê");
        mnuThongKe.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        mniThongKeDoanhThu.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        mniThongKeDoanhThu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/bar-chart.png"))); // NOI18N
        mniThongKeDoanhThu.setText("Thống kê doanh thu");
        mniThongKeDoanhThu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniThongKeDoanhThuActionPerformed(evt);
            }
        });
        mnuThongKe.add(mniThongKeDoanhThu);

        mniThongKeDoanhThuTheoKhachHang.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        mniThongKeDoanhThuTheoKhachHang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/budget.png"))); // NOI18N
        mniThongKeDoanhThuTheoKhachHang.setText("Thống kê doanh thu theo khách hàng");
        mniThongKeDoanhThuTheoKhachHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniThongKeDoanhThuTheoKhachHangActionPerformed(evt);
            }
        });
        mnuThongKe.add(mniThongKeDoanhThuTheoKhachHang);

        mnuTong.add(mnuThongKe);

        mnuHoaDon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/hoadon.png"))); // NOI18N
        mnuHoaDon.setText("Hoá đơn");
        mnuHoaDon.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        mniLapHoaDon.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        mniLapHoaDon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/bill (1).png"))); // NOI18N
        mniLapHoaDon.setText("Lập hoá đơn");
        mniLapHoaDon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniLapHoaDonActionPerformed(evt);
            }
        });
        mnuHoaDon.add(mniLapHoaDon);

        mniThanhToan.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        mniThanhToan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/money-bag.png"))); // NOI18N
        mniThanhToan.setText("Thanh toán");
        mniThanhToan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniThanhToanActionPerformed(evt);
            }
        });
        mnuHoaDon.add(mniThanhToan);

        mnuTong.add(mnuHoaDon);

        mnuDichVu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/dichvu.png"))); // NOI18N
        mnuDichVu.setText("Dịch vụ");
        mnuDichVu.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        mniCapNhatDichVu.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        mniCapNhatDichVu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/storeNav.png"))); // NOI18N
        mniCapNhatDichVu.setText("Cập nhật dịch vụ");
        mniCapNhatDichVu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniCapNhatDichVuActionPerformed(evt);
            }
        });
        mnuDichVu.add(mniCapNhatDichVu);

        mniTimKiemDichVu.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        mniTimKiemDichVu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/invoices.png"))); // NOI18N
        mniTimKiemDichVu.setText("Tìm kiếm dịch vụ");
        mniTimKiemDichVu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniTimKiemDichVuActionPerformed(evt);
            }
        });
        mnuDichVu.add(mniTimKiemDichVu);

        mnuTong.add(mnuDichVu);

        mnuKhuyenMai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/khuyenmai.png"))); // NOI18N
        mnuKhuyenMai.setText("Khuyến mãi");
        mnuKhuyenMai.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        mniCapNhatKhuyenMai.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        mniCapNhatKhuyenMai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/promotion.png"))); // NOI18N
        mniCapNhatKhuyenMai.setText("Cập nhật khuyến mãi");
        mniCapNhatKhuyenMai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniCapNhatKhuyenMaiActionPerformed(evt);
            }
        });
        mnuKhuyenMai.add(mniCapNhatKhuyenMai);

        mniTimKiemKhuyenMai.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        mniTimKiemKhuyenMai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-search-24.png"))); // NOI18N
        mniTimKiemKhuyenMai.setText("Tìm kiếm khuyến mãi");
        mniTimKiemKhuyenMai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniTimKiemKhuyenMaiActionPerformed(evt);
            }
        });
        mnuKhuyenMai.add(mniTimKiemKhuyenMai);

        mnuTong.add(mnuKhuyenMai);

        setJMenuBar(mnuTong);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    
    private void btnHuyPhongChoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHuyPhongChoActionPerformed
        // TODO add your handling code here:
                        String maPDP = txtMaPhieuDatPhong.getText();
                        String maP   = txtMaPhong.getText();
                        DefaultTableModel dftblPDP = (DefaultTableModel)tblDanhSachPhieuDatPhong.getModel();
			//kiem tra trung ma
			try {
				pdp_dao.huyPhieuDatPhong(maPDP,maP);
				
				JOptionPane.showMessageDialog(this, "Huy thanh cong");
			} catch (Exception e2) {
                                JOptionPane.showMessageDialog(this, "Huy không thanh cong");
				e2.printStackTrace();
			}
    }//GEN-LAST:event_btnHuyPhongChoActionPerformed

    private void btnDatPhongChoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDatPhongChoActionPerformed
        // TODO add your handling code here:
        dlgDatPhongCho.setVisible(true);
        dlgDatPhongCho.setSize(700,700);
    }//GEN-LAST:event_btnDatPhongChoActionPerformed
    public boolean kiemTraSDTKhach() {
        ArrayList<KhachHang> dskh = new ArrayList<>();
        KhachHang kh = null;
        String soDT = txtSoDienThoai.getText();
        if (soDT.trim().length() == 0) {
            JOptionPane.showMessageDialog(this, "Bạn chưa nhập số điện thoại Khách");
            txtSoDienThoai.selectAll();
            txtSoDienThoai.requestFocus();
            return false;
        }
        if (!soDT.matches("(^(03)[2-9]\\d{7})|(^(07)[06-9]\\d{7})|(^(08)[1-5]\\d{7})|(^(056)\\d{7})|(^(058)\\d{7})|(^(059)\\d{7})|(^(09)[0-46-9]\\d{7})")) {
            JOptionPane.showMessageDialog(this, "Số điện thoại không đúng địng dạng");
            txtSoDienThoai.selectAll();
            txtSoDienThoai.requestFocus();
            return false;
        }
        kh = khachHang_dao.timKhachHangTheoSoDT(soDT);
        if (kh == null) {
            int xacNhan = JOptionPane.showConfirmDialog(this, "Khách hàng không có trong hệ thống, Bạn có muốn thêm khách hàng không", "Thông báo", JOptionPane.YES_NO_OPTION);
            if (xacNhan == JOptionPane.YES_OPTION) {
                GUICapNhatKhachHang guiKhachHang = new GUICapNhatKhachHang();
                guiKhachHang.setVisible(true);
            }
        } else {
            txtMaKhachHang.setText(kh.getMaKhachHang());
            txtTenKhachHang.setText(kh.getTenKhachHang());
        }
        return true;
    }
    private void btnNhanPhongChoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNhanPhongChoActionPerformed
        // TODO add your handling code here:
        if (txtMaPhong.getText().equals("")||cboNhanVien.getSelectedItem().equals("")||dcNgayDatPhong.getCalendar().equals("")) {
				JOptionPane.showMessageDialog(this, "Bạn chưa điền đủ thông tin");
				return;
			}    
                        HoaDon hoaDon = null;
			Phong maP = new Phong(txtMaPhong.getText());
                        String maKH = txtMaKhachHang.getText();
                        KhachHang kh = null;
                        KhachHang khachHang = new KhachHang(maKH);
                        kh = khachHang_dao.timKhachHangTheoMaKH(maKH);
                        NhanVien maNV = new NhanVien(cboNhanVien.getSelectedItem().toString());
                        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
			String ngayDatPhong = dateFormat.format(dcNgayDatPhong.getDate());
                        String maPDP = pdp_dao.khoiTaoMaPDPC(txtMaPhong.getText(), dcNgayDatPhong.getDate());
                        LocalDateTime localTime = LocalDateTime.now();
                        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss");
                        String gioNhanPhong = localTime.format(formatter);
			PhieuDatPhong x = new PhieuDatPhong( maPDP,maP,khachHang,maNV,ngayDatPhong,gioNhanPhong);
                        DefaultTableModel dftblPDP = (DefaultTableModel)tblDanhSachPhieuDatPhong.getModel();
                               
			try {
                            hoaDon = new HoaDon(maNV, kh.getTenKhachHang(), maP);
                            pdp_dao.themPhieuDatPhong(x);
                            hoaDon_dao.themHoaDon(hoaDon);
				dftblPDP.addRow(new Object[] {x.getMaPhieuDatPhong(),x.getPhong().getMaPhong(),x.getKhachHang().getMaKhachHang(),x.getNhanVien().getMaNhanVien(),x.getNgayDatPhong(),x.getGioNhanPhong()});
                                
				JOptionPane.showMessageDialog(this, "Thêm thành công");
			} catch (Exception e2) {
                                JOptionPane.showMessageDialog(this, "Thêm không thành công");
				e2.printStackTrace();
			}
    }//GEN-LAST:event_btnNhanPhongChoActionPerformed
    private void themDuLieuComboBox() throws SQLException{
        ArrayList<NhanVien> dsNV = nhanVien_dao.layDanhSachNhanVien();
	for(NhanVien x : dsNV)
	{
		cboNhanVien.addItem(x.getMaNhanVien());
	}
    }
    private void btnLamMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLamMoiActionPerformed
        // TODO add your handling code here:
        txtMaPhieuDatPhong.setText("");
        txtMaPhong.setText("");
        txtMaKhachHang.setText("");
        cboNhanVien.setSelectedItem(ABORT);
        
        try {
            docDuLieuTuDataVaoTableDanhSachPhieuDatPhong();
        } catch (SQLException ex) {
            Logger.getLogger(GUICapNhatPhong.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            docDuLieuTuDataVaoTableDanhSachPhongCho();
        } catch (SQLException ex) {
            Logger.getLogger(GUIDatPhongCho.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnLamMoiActionPerformed
    
    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        try {
            themDuLieuComboBox();
        } catch (SQLException ex) {
            Logger.getLogger(GUIDatPhongCho.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            // TODO add your handling code here:
            docDuLieuTuDataVaoTableDanhSachPhongCho();
        } catch (SQLException ex) {
            Logger.getLogger(GUIDatPhongCho.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            docDuLieuTuDataVaoTableDanhSachPhieuDatPhong();
        } catch (SQLException ex) {
            Logger.getLogger(GUIDatPhongCho.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            docDuLieuTuDataVaoTableDanhSachPhongIndlg();
        } catch (SQLException ex) {
            Logger.getLogger(GUIDatPhongCho.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_formComponentShown

    private void pnlDanhSachPhong1ComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_pnlDanhSachPhong1ComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_pnlDanhSachPhong1ComponentShown

    private void tblDanhSachPhongChoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDanhSachPhongChoMouseClicked
        int row = tblDanhSachPhongCho.getSelectedRow();
        String maPhong = tblDanhSachPhongCho.getValueAt(row, 0).toString();
	txtMaPhong.setText(maPhong);
    }//GEN-LAST:event_tblDanhSachPhongChoMouseClicked

    private void tblDanhSachPhongChoComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_tblDanhSachPhongChoComponentShown
        // TODO add your handling code here:

    }//GEN-LAST:event_tblDanhSachPhongChoComponentShown

    private void tblDanhSachPhieuDatPhongFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tblDanhSachPhieuDatPhongFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_tblDanhSachPhieuDatPhongFocusLost

    private void tblDanhSachPhieuDatPhongComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_tblDanhSachPhieuDatPhongComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_tblDanhSachPhieuDatPhongComponentShown

    private void pnlDanhSachPhieuDatPhongComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_pnlDanhSachPhieuDatPhongComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_pnlDanhSachPhieuDatPhongComponentShown

    private void btnXacNhanIndlgDatPhongChoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXacNhanIndlgDatPhongChoActionPerformed
        // TODO add your handling code here:
        if (txtMaPhongIndlg.getText().equals("")) {
				JOptionPane.showMessageDialog(this, "Bạn chưa điền đủ thông tin");
				return;
			}
			
                        String maP = txtMaPhongIndlg.getText();
			Phong x = new Phong( maP);
                        DefaultTableModel dftblPC = (DefaultTableModel)tblDanhSachPhongIndlg.getModel();
			
			try {
				p_dao.chuyenTrangThaiCho(x);
                                dftblPC.addRow(new Object[] {x.getMaPhong(),x.getLoaiPhong().getMaLoaiPhong(),x.getTenPhong(),x.getGiaPhong(),x.getSoNguoiToiDa(),x.getTrangThaiPhong()});
				//docDuLieuTuDataVaoTableDanhSachPhong();
				JOptionPane.showMessageDialog(this, "Cap nhat thanh cong");
			} catch (Exception e2) {
                                JOptionPane.showMessageDialog(this, "Cap nhat không thanh cong");
				e2.printStackTrace();
			}

    }//GEN-LAST:event_btnXacNhanIndlgDatPhongChoActionPerformed

    private void tblDanhSachPhongIndlgMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDanhSachPhongIndlgMouseClicked
        // TODO add your handling code here:
        int row = tblDanhSachPhongIndlg.getSelectedRow();
        String maPhong = tblDanhSachPhongIndlg.getValueAt(row, 0).toString();
	txtMaPhongIndlg.setText(maPhong);
        
    }//GEN-LAST:event_tblDanhSachPhongIndlgMouseClicked

    private void tblDanhSachPhongIndlgComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_tblDanhSachPhongIndlgComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_tblDanhSachPhongIndlgComponentShown

    private void pnlDanhSachPhongComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_pnlDanhSachPhongComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_pnlDanhSachPhongComponentShown

    private void dlgDatPhongChoComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_dlgDatPhongChoComponentShown
        // TODO add your handling code here:
        
    }//GEN-LAST:event_dlgDatPhongChoComponentShown

    private void btnTimPhongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimPhongActionPerformed
        // TODO add your handling code here:
        String maLP = (String)cboLoaiPhong.getSelectedItem();
        String soNguoiToiDa = txtSoNguoiToiDaindlg.getText();
        DefaultTableModel dftbl = (DefaultTableModel)tblDanhSachPhongIndlg.getModel();
        ArrayList<Phong> dsp = p_dao.locPhongTheoLPvsSNTD(maLP,soNguoiToiDa);
        dftbl.setRowCount(0);
        for(Phong x : dsp)
        {
            dftbl.addRow(new Object[] {x.getMaPhong(),x.getLoaiPhong().getMaLoaiPhong(),x.getTenPhong(),x.getGiaPhong(),x.getSoNguoiToiDa(),x.getTrangThaiPhong()});
        }

    }//GEN-LAST:event_btnTimPhongActionPerformed

    private void txtSoNguoiToiDaindlgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSoNguoiToiDaindlgActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSoNguoiToiDaindlgActionPerformed

    private void btnLamMoiIndlgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLamMoiIndlgActionPerformed
        try {
            // TODO add your handling code here:
            //        cboLoaiPhong.setSelectedIndex(0);
            //        cboTrangThai.setSelectedIndex(0);
            docDuLieuTuDataVaoTableDanhSachPhongIndlg();
        } catch (SQLException ex) {
            Logger.getLogger(GUITimKiemPhong.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnLamMoiIndlgActionPerformed

    private void dlgDatPhongChoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dlgDatPhongChoMouseClicked
        // TODO add your handling code here:
        int row = tblDanhSachPhongIndlg.getSelectedRow();
	String maPhong = tblDanhSachPhongIndlg.getValueAt(row, 0).toString();
	txtMaPhongIndlg.setText(maPhong);
    }//GEN-LAST:event_dlgDatPhongChoMouseClicked

    private void cboNhanVienComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_cboNhanVienComponentShown
        
    }//GEN-LAST:event_cboNhanVienComponentShown

    private void tblDanhSachPhieuDatPhongMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDanhSachPhieuDatPhongMouseClicked
        // TODO add your handling code here:
        int row = tblDanhSachPhieuDatPhong.getSelectedRow();
        String maPDP = tblDanhSachPhieuDatPhong.getValueAt(row, 0).toString();
        String maP = tblDanhSachPhieuDatPhong.getValueAt(row, 1).toString();
        String maKH = tblDanhSachPhieuDatPhong.getValueAt(row, 2).toString();
        String maNV = tblDanhSachPhieuDatPhong.getValueAt(row, 3).toString();
        String ngayDatPhong = tblDanhSachPhieuDatPhong.getValueAt(row, 4).toString();
	txtMaPhieuDatPhong.setText(maPDP);
        txtMaPhong.setText(maP);
        txtMaKhachHang.setText(maKH);
        cboNhanVien.setSelectedItem(maNV);
        dcNgayDatPhong.setDateFormatString(ngayDatPhong);
    }//GEN-LAST:event_tblDanhSachPhieuDatPhongMouseClicked

    private void txtSoDienThoaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSoDienThoaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSoDienThoaiActionPerformed

    private void btnKiemTraSDTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKiemTraSDTActionPerformed
        kiemTraSDTKhach();
    }//GEN-LAST:event_btnKiemTraSDTActionPerformed

    private void mniTrangChuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniTrangChuActionPerformed
        GUITrangChu tc = new GUITrangChu();
        tc.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_mniTrangChuActionPerformed

    private void mniTroGiupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniTroGiupActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mniTroGiupActionPerformed

    private void mniCapNhatPhongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniCapNhatPhongActionPerformed
        GUICapNhatPhong cnp = new GUICapNhatPhong();
        cnp.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_mniCapNhatPhongActionPerformed

    private void mniCapNhatLoaiPhongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniCapNhatLoaiPhongActionPerformed
        GUICapNhatLoaiPhong cnlp = new GUICapNhatLoaiPhong();
        cnlp.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_mniCapNhatLoaiPhongActionPerformed

    private void mniTimKiemPhongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniTimKiemPhongActionPerformed
        GUITimKiemPhong tkp = new GUITimKiemPhong();
        tkp.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_mniTimKiemPhongActionPerformed

    private void mniDatPhongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniDatPhongActionPerformed
        // TODO add your handling code here:
        GUIDatPhong ttdp = new GUIDatPhong();
        ttdp.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_mniDatPhongActionPerformed

    private void mniDatPhongChoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniDatPhongChoActionPerformed
        GUIDatPhongCho dpc = new GUIDatPhongCho();
        dpc.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_mniDatPhongChoActionPerformed

    private void mniCapNhatNhanVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniCapNhatNhanVienActionPerformed
        GUICapNhatNhanVien cnnv = new GUICapNhatNhanVien();
        cnnv.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_mniCapNhatNhanVienActionPerformed

    private void mniTimKiemNhanVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniTimKiemNhanVienActionPerformed
        GUITimKiemNhanVien tknv = new GUITimKiemNhanVien();
        tknv.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_mniTimKiemNhanVienActionPerformed

    private void mniCapNhatKhachHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniCapNhatKhachHangActionPerformed
        GUICapNhatKhachHang cnkh = new GUICapNhatKhachHang();
        cnkh.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_mniCapNhatKhachHangActionPerformed

    private void mniTimKiemKhachHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniTimKiemKhachHangActionPerformed
        GUITimKiemKhachHang tkkh = new GUITimKiemKhachHang();
        tkkh.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_mniTimKiemKhachHangActionPerformed

    private void mniThongKeDoanhThuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniThongKeDoanhThuActionPerformed
        GUIThongKeDoanhThu tkdt = new GUIThongKeDoanhThu();
        tkdt.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_mniThongKeDoanhThuActionPerformed

    private void mniThongKeDoanhThuTheoKhachHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniThongKeDoanhThuTheoKhachHangActionPerformed
        GUIThongKeKhachHang tkdtkh = new GUIThongKeKhachHang();
        tkdtkh.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_mniThongKeDoanhThuTheoKhachHangActionPerformed

    private void mniLapHoaDonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniLapHoaDonActionPerformed
        GUILapHoaDon lhd = new GUILapHoaDon();
        lhd.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_mniLapHoaDonActionPerformed

    private void mniThanhToanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniThanhToanActionPerformed
        GUIThanhToan tt = new GUIThanhToan();
        tt.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_mniThanhToanActionPerformed

    private void mniCapNhatDichVuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniCapNhatDichVuActionPerformed
        GUICapNhatDichVu cndv = new GUICapNhatDichVu();
        cndv.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_mniCapNhatDichVuActionPerformed

    private void mniTimKiemDichVuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniTimKiemDichVuActionPerformed
        GUITimKiemDichVu tkdv = new GUITimKiemDichVu();
        tkdv.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_mniTimKiemDichVuActionPerformed

    private void mniCapNhatKhuyenMaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniCapNhatKhuyenMaiActionPerformed
        GUICapNhatKhuyenMai cnkm = new GUICapNhatKhuyenMai();
        cnkm.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_mniCapNhatKhuyenMaiActionPerformed

    private void mniTimKiemKhuyenMaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniTimKiemKhuyenMaiActionPerformed
        GUITimKiemKhuyenMai tkkm = new GUITimKiemKhuyenMai();
        tkkm.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_mniTimKiemKhuyenMaiActionPerformed
                                               
    private void themDuLieuComboBoxIndlg() throws SQLException{
        ArrayList<Phong> dsP = p_dao.getAllPhong();
		for(Phong x : dsP)
		{
			cboLoaiPhong.addItem(x.getLoaiPhong().getMaLoaiPhong());
                        
		}
    }
        public void docDuLieuTuDataVaoTableDanhSachPhongIndlg() throws SQLException 
	{  
            DefaultTableModel dftblPC = (DefaultTableModel)tblDanhSachPhongIndlg.getModel();
            ArrayList<Phong> listpc = p_dao.getAllPhongTrong();
            dftblPC.setRowCount(0);
		for(Phong x : listpc)
		{
			dftblPC.addRow(new Object[] {x.getMaPhong(),x.getLoaiPhong().getMaLoaiPhong(),x.getTenPhong(),x.getGiaPhong(),x.getSoNguoiToiDa(),x.getTrangThaiPhong()});
		}
        }
    public void docDuLieuTuDataVaoTableDanhSachPhongCho() throws SQLException 
	{  
            DefaultTableModel dftblPC = (DefaultTableModel)tblDanhSachPhongCho.getModel();
            ArrayList<Phong> listpc = p_dao.getAllPhongCho();
            dftblPC.setRowCount(0);
		for(Phong x : listpc)
		{
			dftblPC.addRow(new Object[] {x.getMaPhong(),x.getLoaiPhong().getMaLoaiPhong(),x.getTenPhong(),x.getGiaPhong(),x.getSoNguoiToiDa(),x.getTrangThaiPhong()});
		}
        }
    public void docDuLieuTuDataVaoTableDanhSachPhieuDatPhong() throws SQLException 
	{  
            DefaultTableModel dftblPDP = (DefaultTableModel)tblDanhSachPhieuDatPhong.getModel();
            ArrayList<PhieuDatPhong> listpdp = pdp_dao.getAllPhieuDatPhong();
            dftblPDP.setRowCount(0);
		for(PhieuDatPhong x : listpdp)
		{
			dftblPDP.addRow(new Object[] {x.getMaPhieuDatPhong(),x.getPhong().getMaPhong(),x.getKhachHang().getMaKhachHang(),x.getNhanVien().getMaNhanVien(),x.getNgayDatPhong(),x.getGioNhanPhong()});
		}
        }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUICapNhatPhong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUICapNhatPhong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUICapNhatPhong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUICapNhatPhong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIDatPhongCho().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDatPhongCho;
    private javax.swing.JButton btnHuyPhongCho;
    private javax.swing.JButton btnKiemTraSDT;
    private javax.swing.JButton btnLamMoi;
    private javax.swing.JButton btnLamMoiIndlg;
    private javax.swing.JButton btnNhanPhongCho;
    private javax.swing.JButton btnQuayLaiFromDatPhongCho;
    private javax.swing.JButton btnTimPhong;
    private javax.swing.JButton btnXacNhanIndlgDatPhongCho;
    public javax.swing.JComboBox<String> cboLoaiPhong;
    private javax.swing.JComboBox<String> cboNhanVien;
    private com.toedter.calendar.JDateChooser dcNgayDatPhong;
    private javax.swing.JDialog dlgDatPhongCho;
    private javax.swing.JLabel lblGio;
    private javax.swing.JLabel lblMaKhachHang1;
    private javax.swing.JLabel lblMaLoaiPhong;
    private javax.swing.JLabel lblMaNhanVien;
    private javax.swing.JLabel lblMaPhieuDatPhong;
    private javax.swing.JLabel lblMaPhong;
    private javax.swing.JLabel lblMaPhongIndlg;
    private javax.swing.JLabel lblNgay;
    private javax.swing.JLabel lblNgayLap1;
    private javax.swing.JLabel lblNgayLap3;
    private javax.swing.JLabel lblSoNguoiToiDaindlg;
    private javax.swing.JLabel lblTenKhachHang;
    private javax.swing.JLabel lblTieuDe;
    private javax.swing.JMenu mnHeThong;
    private javax.swing.JMenuItem mniCapNhatDichVu;
    private javax.swing.JMenuItem mniCapNhatKhachHang;
    private javax.swing.JMenuItem mniCapNhatKhuyenMai;
    private javax.swing.JMenuItem mniCapNhatLoaiPhong;
    private javax.swing.JMenuItem mniCapNhatNhanVien;
    private javax.swing.JMenuItem mniCapNhatPhong;
    private javax.swing.JMenuItem mniDangXuat;
    private javax.swing.JMenuItem mniDatPhong;
    private javax.swing.JMenuItem mniDatPhongCho;
    private javax.swing.JMenuItem mniLapHoaDon;
    private javax.swing.JMenuItem mniThanhToan;
    private javax.swing.JMenuItem mniThongKeDoanhThu;
    private javax.swing.JMenuItem mniThongKeDoanhThuTheoKhachHang;
    private javax.swing.JMenuItem mniTimKiemDichVu;
    private javax.swing.JMenuItem mniTimKiemKhachHang;
    private javax.swing.JMenuItem mniTimKiemKhuyenMai;
    private javax.swing.JMenuItem mniTimKiemNhanVien;
    private javax.swing.JMenuItem mniTimKiemPhong;
    private javax.swing.JMenuItem mniTrangChu;
    private javax.swing.JMenuItem mniTroGiup;
    private javax.swing.JMenu mnuDichVu;
    private javax.swing.JMenu mnuHoaDon;
    private javax.swing.JMenu mnuKhachHang;
    private javax.swing.JMenu mnuKhuyenMai;
    private javax.swing.JMenu mnuNhanVien;
    private javax.swing.JMenu mnuPhong;
    private javax.swing.JMenu mnuThongKe;
    private javax.swing.JMenuBar mnuTong;
    private javax.swing.JPanel pnlDanhSachPhieuDatPhong;
    private javax.swing.JPanel pnlDanhSachPhong;
    private javax.swing.JPanel pnlDanhSachPhong1;
    private javax.swing.JPanel pnlThongTinKhachHang;
    private javax.swing.JPanel pnlTieuDe3;
    private javax.swing.JScrollPane scrDanhSachPhong;
    private javax.swing.JScrollPane scrDanhSachPhong1;
    private javax.swing.JScrollPane scrDanhSachPhong2;
    private javax.swing.JTable tblDanhSachPhieuDatPhong;
    private javax.swing.JTable tblDanhSachPhongCho;
    private javax.swing.JTable tblDanhSachPhongIndlg;
    private javax.swing.JTextField txtMaKhachHang;
    private javax.swing.JTextField txtMaPhieuDatPhong;
    private javax.swing.JTextField txtMaPhong;
    private javax.swing.JTextField txtMaPhongIndlg;
    private javax.swing.JTextField txtSoDienThoai;
    public javax.swing.JTextField txtSoNguoiToiDaindlg;
    private javax.swing.JTextField txtTenKhachHang;
    // End of variables declaration//GEN-END:variables
}
